from rapidfuzz import fuzz
from typing import List

def select_sql_db(user_query: str, db_schemas: List[str]) -> List[str]:
    """
    Ranks database schema descriptions by fuzzy similarity to a user query.

    This function compares each schema description against the user query
    using fuzzy string matching and returns the list of schema descriptions
    sorted from most to least relevant.

    Parameters:
        user_query (str): The natural language query or keyword input by the user.
        db_schemas (List[str]): A list of schema description strings (one per table),
                                 typically generated by describe_sql.

    Returns:
        List[str]: The input schema descriptions sorted by relevance to the query,
                   with the best match appearing first.
    """
    ranked = sorted(
        db_schemas,
        key=lambda schema: fuzz.token_sort_ratio(user_query, schema),
        reverse=True
    )
    return ranked
